import type { TileGrid, TileLayer } from '../../models/tilemap';
import { TILE_EMPTY, getTile, setTile, inBounds } from '../../models/tilemap';

/**
 * Standard wall tile IDs used by the procedural renderer. The IDs match
 * those generated by `generateProceduralAtlas` (floor tiles 1-6, then
 * wall variants starting at 7).
 */
export const STANDARD_WALL_IDS: Record<string, number> = {
  wall_island: 7,
  wall_end_n: 8,
  wall_end_e: 9,
  wall_end_s: 10,
  wall_end_w: 11,
  wall_edge_ns: 12,
  wall_edge_ew: 13,
  wall_corner_ne: 14,
  wall_corner_se: 15,
  wall_corner_sw: 16,
  wall_corner_nw: 17,
  wall_t_n: 18,
  wall_t_e: 19,
  wall_t_s: 20,
  wall_t_w: 21,
  wall_cross: 22,
};

export const STANDARD_FLOOR_IDS = [1, 2, 3, 4];

// Cardinal direction bits for 4-bit mask
const N = 1;
const E = 2;
const S = 4;
const W = 8;

/**
 * 4-bit cardinal neighbor mask. A bit is set when the neighbor cell is
 * non-empty.  N=1, E=2, S=4, W=8.
 */
export function computeNeighborMask4(
  layer: TileLayer,
  grid: TileGrid,
  x: number,
  y: number,
): number {
  let mask = 0;
  if (getTile(layer, grid, x, y - 1) !== TILE_EMPTY) mask |= N;
  if (getTile(layer, grid, x + 1, y) !== TILE_EMPTY) mask |= E;
  if (getTile(layer, grid, x, y + 1) !== TILE_EMPTY) mask |= S;
  if (getTile(layer, grid, x - 1, y) !== TILE_EMPTY) mask |= W;
  return mask;
}

// 8-direction bits: N=1, NE=2, E=4, SE=8, S=16, SW=32, W=64, NW=128
const N8 = 1;
const NE8 = 2;
const E8 = 4;
const SE8 = 8;
const S8 = 16;
const SW8 = 32;
const W8 = 64;
const NW8 = 128;

/**
 * 8-bit neighbor mask including diagonals.
 * N=1, NE=2, E=4, SE=8, S=16, SW=32, W=64, NW=128.
 */
export function computeNeighborMask8(
  layer: TileLayer,
  grid: TileGrid,
  x: number,
  y: number,
): number {
  let mask = 0;
  if (getTile(layer, grid, x, y - 1) !== TILE_EMPTY) mask |= N8;
  if (getTile(layer, grid, x + 1, y - 1) !== TILE_EMPTY) mask |= NE8;
  if (getTile(layer, grid, x + 1, y) !== TILE_EMPTY) mask |= E8;
  if (getTile(layer, grid, x + 1, y + 1) !== TILE_EMPTY) mask |= SE8;
  if (getTile(layer, grid, x, y + 1) !== TILE_EMPTY) mask |= S8;
  if (getTile(layer, grid, x - 1, y + 1) !== TILE_EMPTY) mask |= SW8;
  if (getTile(layer, grid, x - 1, y) !== TILE_EMPTY) mask |= W8;
  if (getTile(layer, grid, x - 1, y - 1) !== TILE_EMPTY) mask |= NW8;
  return mask;
}

/**
 * Maps a 4-bit cardinal neighbor mask (which neighbors are also walls)
 * to a wall tile role string.  All 16 cases are covered.
 */
export const WALL_AUTOTILE_16: Record<number, string> = {
  [0]:                       'wall_island',
  [N]:                       'wall_end_n',
  [E]:                       'wall_end_e',
  [N | E]:                   'wall_corner_ne',
  [S]:                       'wall_end_s',
  [N | S]:                   'wall_edge_ns',
  [E | S]:                   'wall_corner_se',
  [N | E | S]:               'wall_t_e',
  [W]:                       'wall_end_w',
  [N | W]:                   'wall_corner_nw',
  [E | W]:                   'wall_edge_ew',
  [N | E | W]:               'wall_t_n',
  [S | W]:                   'wall_corner_sw',
  [N | S | W]:               'wall_t_w',
  [E | S | W]:               'wall_t_s',
  [N | E | S | W]:           'wall_cross',
};

/**
 * 47-tile blob lookup. Maps an 8-bit neighbor mask to a tile index (0-46).
 * Diagonals only matter when both adjacent cardinals are present.
 * The canonical 47-tile blob set (used by RPG Maker and Tiled terrain sets).
 */
function reduce8to47(mask8: number): number {
  const n  = (mask8 & N8) !== 0;
  const ne = (mask8 & NE8) !== 0;
  const e  = (mask8 & E8) !== 0;
  const se = (mask8 & SE8) !== 0;
  const s  = (mask8 & S8) !== 0;
  const sw = (mask8 & SW8) !== 0;
  const w  = (mask8 & W8) !== 0;
  const nw = (mask8 & NW8) !== 0;

  const cne = n && e ? (ne ? 1 : 0) : 0;
  const cse = s && e ? (se ? 1 : 0) : 0;
  const csw = s && w ? (sw ? 1 : 0) : 0;
  const cnw = n && w ? (nw ? 1 : 0) : 0;

  const cardinal = (n ? N : 0) | (e ? E : 0) | (s ? S : 0) | (w ? W : 0);
  const diag = (cne << 0) | (cse << 1) | (csw << 2) | (cnw << 3);

  return BLOB_47_TABLE[cardinal * 16 + diag] ?? 0;
}

const BLOB_47_TABLE: Record<number, number> = {};

(function buildBlob47Table() {
  let idx = 0;
  const assign = (card: number, diagPattern: number) => {
    BLOB_47_TABLE[card * 16 + diagPattern] = idx++;
  };

  assign(0, 0);
  assign(N, 0);
  assign(E, 0);
  assign(S, 0);
  assign(W, 0);
  assign(N|E, 0); assign(N|E, 1);
  assign(E|S, 0); assign(E|S, 2);
  assign(S|W, 0); assign(S|W, 4);
  assign(N|W, 0); assign(N|W, 8);
  assign(N|S, 0);
  assign(E|W, 0);
  assign(N|E|S, 0); assign(N|E|S, 1); assign(N|E|S, 2); assign(N|E|S, 3);
  assign(E|S|W, 0); assign(E|S|W, 2); assign(E|S|W, 4); assign(E|S|W, 6);
  assign(N|S|W, 0); assign(N|S|W, 4); assign(N|S|W, 8); assign(N|S|W, 12);
  assign(N|E|W, 0); assign(N|E|W, 1); assign(N|E|W, 8); assign(N|E|W, 9);
  assign(N|E|S|W, 0);
  assign(N|E|S|W, 1); assign(N|E|S|W, 2); assign(N|E|S|W, 3);
  assign(N|E|S|W, 4); assign(N|E|S|W, 5); assign(N|E|S|W, 6); assign(N|E|S|W, 7);
  assign(N|E|S|W, 8); assign(N|E|S|W, 9); assign(N|E|S|W, 10); assign(N|E|S|W, 11);
  assign(N|E|S|W, 12); assign(N|E|S|W, 13); assign(N|E|S|W, 14); assign(N|E|S|W, 15);
})();

/**
 * Replace uniform wall markers with correct tile variants based on their
 * cardinal wall-neighbors. Uses 16-tile cardinal-only mapping.
 *
 * `wallTileIds` maps role strings (from WALL_AUTOTILE_16) to actual tile IDs
 * in the asset pack, e.g. `{ wall_corner_ne: 42, wall_edge_ns: 43, … }`.
 */
export function autotileWallLayer(
  grid: TileGrid,
  wallTileIds: Record<string, number>,
): void {
  const wallLayer = grid.layers.walls;
  const { width, height } = grid;

  for (let y = 0; y < height; y++) {
    for (let x = 0; x < width; x++) {
      const current = getTile(wallLayer, grid, x, y);
      if (current === TILE_EMPTY) continue;

      const mask8 = computeNeighborMask8(wallLayer, grid, x, y);
      const blobIdx = reduce8to47(mask8);

      let cardinal = 0;
      if (inBounds(grid, x, y - 1) && getTile(wallLayer, grid, x, y - 1) !== TILE_EMPTY) cardinal |= N;
      if (inBounds(grid, x + 1, y) && getTile(wallLayer, grid, x + 1, y) !== TILE_EMPTY) cardinal |= E;
      if (inBounds(grid, x, y + 1) && getTile(wallLayer, grid, x, y + 1) !== TILE_EMPTY) cardinal |= S;
      if (inBounds(grid, x - 1, y) && getTile(wallLayer, grid, x - 1, y) !== TILE_EMPTY) cardinal |= W;

      const role = WALL_AUTOTILE_16[cardinal];
      if (role !== undefined && role in wallTileIds) {
        let tileId = wallTileIds[role]!;
        if (blobIdx > 0) {
          tileId = tileId + (blobIdx % 4) * 0;
        }
        setTile(wallLayer, grid, x, y, tileId);
      }
    }
  }
}

/**
 * Add visual variation to floor tiles by deterministically choosing from
 * `floorTileIds` using a spatial hash.
 */
export function autotileFloorVariation(
  grid: TileGrid,
  floorTileIds: number[],
  seed: number,
): void {
  if (floorTileIds.length === 0) return;

  const floorLayer = grid.layers.floor;
  const { width, height } = grid;
  const count = floorTileIds.length;

  for (let y = 0; y < height; y++) {
    for (let x = 0; x < width; x++) {
      if (getTile(floorLayer, grid, x, y) === TILE_EMPTY) continue;
      const idx = ((x * 7919 + y * 104729 + seed) >>> 0) % count;
      setTile(floorLayer, grid, x, y, floorTileIds[idx]!);
    }
  }
}
